spring: 
  profile: 
    active: 
    - dev
---
spring: 
  profile: dev
    aplication: 
      name: microservicecloud-config-atguigu-dev
---
spring: 
  profile: test
  aplication: 
    name: microservicecloud-config-atguigu-test
#保存为UTF-8